version: 2.1
orbs:
  node: circleci/node@4.1.0
  ruby: circleci/ruby@1.1.3
  android: circleci/android@1.0.3

# --------------------------------
# common : executors
# --------------------------------

executors:
  node:
    docker:
      - image: circleci/node:14.16.0-stretch
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    resource_class: large

# --------------------------------
# common : commands
# --------------------------------

commands:
  audit:
    description: 'Audit CI'
    steps:
      - run: npm run npm:audit
  lint:
    description: 'Lint'
    steps:
      - run:
          name: 'Lint'
          command: npm run code:lint
  test:
    description: 'Test'
    steps:
      - run:
          name: 'Test'
          command: npm run test
          environment:
            - NODE_OPTIONS: --max_old_space_size=8192
  env:
    description: 'Setup Env File'
    steps:
      - run:
          name: 'Create Test Env'
          command: npm run env:test
  bundle:
    description: 'Bundle Android JS code'
    steps:
      - run:
          name: 'Bundle Android JS code'
          command: npm run bundle:android
  setup-node:
    description: 'Setup the node environment'
    steps:
      - node/install:
          node-version: 14.16.0
          install-npm: false
      - node/install-packages:
          cache-version: v1-{{ arch }}
  setup-ruby:
    description: 'Setup ruby and install packages'
    steps:
      - run: echo 'chruby ruby-2.7' >> ~/.bash_profile
      - run: gem update bundler
      - ruby/install-deps:
          key: gems-v1-{{ arch }}

  create_keystore:
    description: 'Create Keystore for PlayStore'
    steps:
      - run:
          name: Create the keystore file for Google PlayStore from env variable
          command: npm run create:keystore

  deploy-android-internal:
    description: 'Deploy the Android app to Google PlayStore on the Internal track'
    steps:
      - run:
          name: 'Deploy the Android app to Google PlayStore on the Internal testing track'
          working_directory: ~/project
          resource_class: large
          command: bundle exec fastlane android deploy_internal

# --------------------------------
# common : jobs
# --------------------------------

jobs:
  pull-request:
    executor: node
    steps:
      - checkout
      - node/install-packages
      - audit
      - lint
      - env
      - test
      - bundle

  deploy-android-internal:
    working_directory: ~/project
    executor: android/android
    steps:
      - checkout
      - setup-node
      - setup-ruby
      - env
      - create_keystore
      - deploy-android-internal
# --------------------------------
# common : workflows
# --------------------------------

workflows:
  version: 2
  validate-branch:
    jobs:
      - pull-request:
          filters:
            branches:
              ignore:
                - YOMA-474_setup_app_for_alpha_deployment_to_playstore
                - develop
                - main
  deploy-android-internal:
    jobs:
      - pull-request:
          filters:
            branches:
              only:
                - YOMA-474_setup_app_for_alpha_deployment_to_playstore
                - develop
                - main
      - deploy-android-internal:
          requires:
            - pull-request
