export enum Colors {
  backgroundGrey = 'backgroundGrey',
  fontBlue = 'fontBlue',
  lightGrey = 'lightGrey',
  lightYellow = 'lightYellow',
  menuGrey = 'menuGrey',
  primaryBlue = 'primaryBlue',
  primaryDarkGrey = 'primaryDarkGrey',
  primaryGreen = 'primaryGreen',
  primaryPurple = 'primaryPurple',
  primaryRed = 'primaryRed',
  primaryYellow = 'primaryYellow',
  secondaryBlue = 'secondaryBlue',
  secondaryDarkBlue = 'secondaryDarkBlue',
  secondaryGreen = 'secondaryGreen',
  secondaryKhaki = 'secondaryKhaki',
  secondaryPurple = 'secondaryPurple',
  secondaryRed = 'secondaryRed',
  transparent = 'transparent',
  unsavedStyleLightBlue = 'unsavedStyleLightBlue',
  unsavedStyleLightGrey = 'unsavedStyleLightGrey',
  unsavedStyleLightRed = 'unsavedStyleLightRed',
  white = 'white',
}

export enum FontFamily {
  small = 'small',
  medium = 'medium',
  semibold = 'semibold',
  bold = 'bold',
}
