export enum Colors {
  BackgroundGrey = 'backgroundGrey',
  Black = 'black',
  DarkGrey02 = 'darkGrey02',
  FacebookBlue = 'facebookBlue',
  FontBlue = 'fontBlue',
  GoogleRed = 'googleRed',
  LightGrey = 'lightGrey',
  LightYellow = 'lightYellow',
  MenuGrey = 'menuGrey',
  PrimaryBlue = 'primaryBlue',
  PrimaryDarkGrey = 'primaryDarkGrey',
  PrimaryGreen = 'primaryGreen',
  PrimaryPurple = 'primaryPurple',
  PrimaryRed = 'primaryRed',
  PrimaryYellow = 'primaryYellow',
  SecondaryBlue = 'secondaryBlue',
  SecondaryDarkBlue = 'secondaryDarkBlue',
  SecondaryGreen = 'secondaryGreen',
  SecondaryKhaki = 'secondaryKhaki',
  SecondaryPurple = 'secondaryPurple',
  SecondaryRed = 'secondaryRed',
  Transparent = 'transparent',
  White = 'white',
}

export enum FontFamily {
  Small = 'small',
  Medium = 'medium',
  Semibold = 'semibold',
  Bold = 'bold',
}
