import * as SUT from './Challenges.middleware'

describe('modules/User/Challenges/Challenges.middleware', () => {
  describe('getChallengesFromFetchCredentialsFlow', () => {
    it('should correctly handle being called', () => {
      // given ...
      // when ...
      const result = SUT.getChallengesFromFetchCredentialsFlow()
      // then ...
      expect(result).toEqual()
    })
    it('should', () => {
      // given ...
      // when ...
      const result = SUT.getChallengesFromFetchCredentialsFlow()
      // then ...
      expect(result).toEqual()
    })
  })
  describe('normaliseChallengesFlow', () => {
    it('should correctly handle being called', () => {
      // given ...
      // when ...
      const result = SUT.normaliseChallengesFlow()
      // then ...
      expect(result).toEqual()
    })
    it('should ', () => {
      // given ...
      // when ...
      const result = SUT.normaliseChallengesFlow()
      // then ...
      expect(result).toEqual()
    })
  })
  describe('setChallengesFlow', () => {
    it('should correctly handle being called', () => {
      // given ...
      // when ...
      const result = SUT.setChallengesFlow()
      // then ...
      expect(result).toEqual()
    })
    it('should ', () => {
      // given ...
      // when ...
      const result = SUT.setChallengesFlow()
      // then ...
      expect(result).toEqual()
    })
  })
})
