const API_BASE_USERS = 'users'
const API_NAMES_PART = 'names'
const API_ORGANISATIONS_PART = 'organisations'
const API_PART_CREDENTIALS = 'credentials'

export { API_BASE_USERS, API_NAMES_PART, API_ORGANISATIONS_PART, API_PART_CREDENTIALS }
