default_platform(:android)

platform :android do
  desc "Android beta deploy"

  lane :clean do
    build_android_app(task: 'clean', project_dir: './android')
  end

  lane :build do
    gradle(
        task: "assemble",
        build_type: "Release",
        project_dir: './android',
        print_command: false,
        flags: "--no-daemon --max-workers 2"
      )
  end

  lane :distribute do
    clean
    build
    firebase_app_distribution(
      app: '1:1007644634835:android:8825d8828e786999602e26',
      groups: 'yoma-testers',
      firebase_cli_token: ENV['FIREBASE_TOKEN'],
      release_notes: 'Testing builds via fastlane',
      android_artifact_type:'APK',
      debug: true,
    )
    slack(
      message: "Build successfully deployed to Firebase App Distribution."
    )
  end
end
