default_platform(:android)

platform :android do
  desc "Android beta deploy"

  lane :clean do
    build_android_app(task: 'clean', project_dir: './android')
  end

  lane :build do
    gradle(
        task: "assemble",
        build_type: "Release",
        project_dir: './android',
        print_command: false,
        flags: "--no-daemon --max-workers 2"
      )
  end

  lane :distribute do

    increment_version_code(
      gradle_file_path: "./app/build.gradle"
    )

    clean
    build
    firebase_app_distribution(
      app: ENV['FIREBASE_APP_ID_ALPHA'],
      groups: 'yoma-testers',
      firebase_cli_token: ENV['FIREBASE_TOKEN'],
      release_notes_file: './release-notes.txt',
      android_artifact_type:'APK',
      debug: true,
    )
  end
end
