import { prop } from 'ramda'

import * as SUT from './ramda.utils'

describe('src/utils/ramda.utils', () => {
  describe('objFromListWith', () => {
    it('should return an object from a given list with the keys generated by the given function', () => {
      // given ...

      // when ...
      const result = SUT.objFromListWith(prop('id'), [
        {
          id: 'id1',
          other: 'OTHER DATA',
        },
        {
          id: 'id2',
          other: 'OTHER OTHER DATA',
        },
      ])

      // then ...
      expect(result).toEqual({
        id1: {
          id: 'id1',
          other: 'OTHER DATA',
        },
        id2: {
          id: 'id2',
          other: 'OTHER OTHER DATA',
        },
      })
    })
  })
})
