declare module 'ramda' {
  export function __(...rest: any[]): any[]
  export function always(...rest: any[]): any[]
  export function append(...rest: any[]): any
  export function concat(...rest: any[]): any[]
  export function curry(...rest: any[]): any[]
  export function complement(...rest: any[]): any
  export function equals(...rest: any[]): any
  export function evolve(...rest: any[]): any
  export function filter(...rest: any[]): any
  export function flatten(...rest: any[]): any[]
  export function head(...rest: any[]): any
  export function identity(...rest: any[]): any
  export function ifElse(...rest: any[]): any
  export function join(...rest: any[]): any
  export function juxt(...rest: any[]): any
  export function isNil(...rest: any[]): any[]
  export function map(...rest: any[]): any
  export function mergeAll(...rest: any[]): any
  export function mergeRight(...rest: any[]): any
  export function mergeDeepRight(...rest: any[]): any
  export function multiply(...rest: any[]): number
  export function not(...rest: any[]): number
  export function objOf(...rest: any[]): any
  export function of(...rest: any[]): any[]
  export function pipe(...rest: any[]): any
  export function path(...rest: any[]): any
  export function pathOr(...rest: any[]): any
  export function pick(...rest: any[]): any
  export function prepend(...rest: any[]): any
  export function reduce(...rest: any[]): any[]
  export function reduceRight(...rest: any[]): any[]
  export function tail(...rest: any[]): any[]
  export function tap(...rest: any[]): any[]
  export function toUpper(...rest: any[]): any
  export function trim(...rest: any[]): any
  export function unless(...rest: any[]): any
  export function when(...rest: any[]): any
  export function mergeDeepRight(...rest: any[]): any[]
}
